# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfea0e0ceb80bf08f58925e1a43f19fb19a61c054afec8effa11211eaa6023d2c6b78592603dcaf28d72144e33f598e0f18b9ace9f308c90b5abe539e549281d

test:
  secret_key_base: 55934f2c1d836fa3807986157b7392fb215b1c7c634a5a37ec9d106759552a0eac8e5ec4e07a71b049108e7f3b5d1d8cf75ab92c635d3d87b7e5516cd44ead0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
